org: leonwright
app: pokemonapp
service: pokemon-backend

frameworkVersion: '3'

custom:
  tableName: !ImportValue MainStack-TableName
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.9
  region: sa-east-1
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
             - Fn::Join:
                - ""
                - - "arn:aws:dynamodb:"
                  - Ref: "AWS::Region"
                  - ":"
                  - Ref: "AWS::AccountId"
                  - ":table/"
                  - !ImportValue MainStack-TableName
  environment:
    USERS_TABLE: !ImportValue MainStack-TableName

functions:
  auth:
    handler: handlers.auth
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          authorizer: auth
          cors: true

plugins:
  - serverless-wsgi
  - serverless-python-requirements
