version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "blocks-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-dyb2g4pvamj8"
s3_prefix = "blocks-stack"
region = "sa-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
